FROM node:20-alpine AS base

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm ci

FROM base AS development

ENV NODE_ENV=development

WORKDIR /app

COPY turbo.json ./
COPY package*.json ./

COPY packages ./packages
COPY apps/web ./apps/web

RUN npm install

RUN cd packages/database && npx prisma generate

WORKDIR /app/apps/web

EXPOSE 3000

CMD ["npm", "run", "dev"]
